server {
  listen       80;
  server_name  _;

  root /usr/share/nginx/html;
  index index.html;

  # Soporta SPA: si no hay archivo, devuelve index.html
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Servir archivos estáticos con cache razonable
  location ~* \.(?:css|js|json|xml|jpg|jpeg|png|gif|ico|svg)$ {
    try_files $uri =404;
    expires 7d;
    add_header Cache-Control "public";
  }

  # Evitar cache en index.html para que siempre cargue la última versión
  location = /index.html {
    add_header Cache-Control "no-cache, no-store, must-revalidate";
  }
}
