INSERT INTO usuarios (nombre, password, rol) VALUES
    ('admin', 'Admin123!', TRUE),
    ('jose', 'Jose123!', FALSE),
    ('juan', 'Juan123!', FALSE);

INSERT INTO barajas (nombre, descripcion, idUsuario) VALUES
    ('gitflow', 'Ramas, commits y rescates de ultima hora.', 1),
    ('backend', 'API REST, controladores y errores con dignidad.', 1),
    ('frontend', 'React, vistas, estado y avisos visuales.', 2),
    ('database', 'Tablas, relaciones y datos que no se pierden.', 2),
    ('devops-testing', 'Docker, CI, Postman y comprobaciones finales.', 3);

INSERT INTO cartas (nombre, valor, tipoResultado, idBaraja) VALUES
    ('RAMA LIMPIA', 1, 'APTO', 1),
    ('COMMIT COJO', 2, 'NO_APTO', 1),
    ('MERGE DRAMA', 3, 'NO_APTO', 1),
    ('PUSH FELIZ', 4, 'APTO', 1),
    ('REBASE SUSTO', 5, 'PRUEBA_OTRA_VEZ', 1),
    ('STASH SALVADOR', 6, 'APTO', 1),
    ('CONFLICTO', 7, 'NO_APTO', 1),
    ('RAMA PERDIDA', 8, 'NO_APTO', 1),
    ('PR VERDE', 9, 'APTO', 1),
    ('HISTORIAL RARO', 10, 'NO_APTO', 1),
    ('TAG TIMIDO', 11, 'PRUEBA_OTRA_VEZ', 1),
    ('REVIEW DURO', 12, 'NO_APTO', 1),

    ('RUTA CLARA', 1, 'APTO', 2),
    ('BODY VACIO', 2, 'NO_APTO', 2),
    ('SQL ENFADADO', 3, 'NO_APTO', 2),
    ('JSON LIMPIO', 4, 'APTO', 2),
    ('422 CERTERO', 5, 'APTO', 2),
    ('500 FANTASMA', 6, 'NO_APTO', 2),
    ('CORS MISTERIO', 7, 'PRUEBA_OTRA_VEZ', 2),
    ('ID PERDIDO', 8, 'NO_APTO', 2),
    ('CTRL FINO', 9, 'APTO', 2),
    ('VALIDA TARDE', 10, 'NO_APTO', 2),
    ('POOL SECO', 11, 'PRUEBA_OTRA_VEZ', 2),
    ('404 SALUDA', 12, 'NO_APTO', 2),

    ('COMPONENTE OK', 1, 'APTO', 3),
    ('ESTADO LOCO', 2, 'NO_APTO', 3),
    ('FETCH CAIDO', 3, 'NO_APTO', 3),
    ('ALERTA BONITA', 4, 'APTO', 3),
    ('FORM REBELDE', 5, 'NO_APTO', 3),
    ('NAV CENTRADA', 6, 'APTO', 3),
    ('CSS MORDISCO', 7, 'PRUEBA_OTRA_VEZ', 3),
    ('RUTA PERDIDA', 8, 'NO_APTO', 3),
    ('BUILD VERDE', 9, 'APTO', 3),
    ('PROP OLVIDADA', 10, 'NO_APTO', 3),
    ('INPUT TRAMPA', 11, 'PRUEBA_OTRA_VEZ', 3),
    ('CARD TORCIDA', 12, 'NO_APTO', 3),

    ('FK FELIZ', 1, 'APTO', 4),
    ('ID NULO', 2, 'NO_APTO', 4),
    ('TABLA COJA', 3, 'NO_APTO', 4),
    ('SEED SABROSO', 4, 'APTO', 4),
    ('DATO HUIDO', 5, 'NO_APTO', 4),
    ('JOIN MENTAL', 6, 'PRUEBA_OTRA_VEZ', 4),
    ('PK FIRME', 7, 'APTO', 4),
    ('DELETE PELIGRO', 8, 'NO_APTO', 4),
    ('RELACION OK', 9, 'APTO', 4),
    ('CAMPO LARGO', 10, 'NO_APTO', 4),
    ('ENUM GRUNON', 11, 'PRUEBA_OTRA_VEZ', 4),
    ('DB SIN CAFE', 12, 'NO_APTO', 4),

    ('CI VERDE', 1, 'APTO', 5),
    ('NPM DRAMA', 2, 'NO_APTO', 5),
    ('NEWMAN RUN', 3, 'APTO', 5),
    ('POSTMAN ROJO', 4, 'NO_APTO', 5),
    ('DOCKER SUBE', 5, 'APTO', 5),
    ('PUERTO OCUPADO', 6, 'NO_APTO', 5),
    ('ENV PERDIDO', 7, 'NO_APTO', 5),
    ('BUILD FINAL', 8, 'APTO', 5),
    ('LOG INFINITO', 9, 'PRUEBA_OTRA_VEZ', 5),
    ('CHECK CAIDO', 10, 'NO_APTO', 5),
    ('CACHE RARA', 11, 'PRUEBA_OTRA_VEZ', 5),
    ('RELEASE TEMBLA', 12, 'NO_APTO', 5);

INSERT INTO tarjetas (titulo, contenido, idBaraja) VALUES
    ('Crear rama', 'Antes de tocar codigo, crea una rama clara. Asi cada tarea queda aislada y el historial se entiende.', 1),
    ('Commit util', 'Un commit debe guardar una idea concreta. Si mezcla cinco temas, luego nadie sabe que rompiste con estilo.', 1),
    ('Rebase', 'Sirve para traer cambios remotos y colocar tus commits encima. Si se complica, respira y revisa conflicto por conflicto.', 1),
    ('Pull request', 'El PR resume que cambiaste, como lo probaste y por que tiene sentido integrarlo.', 1),
    ('Git status', 'Mirar git status antes de actuar evita subir basura, olvidar archivos o inventar una tragedia innecesaria.', 1),

    ('Ruta y controlador', 'La ruta define la URL y el controlador hace el trabajo: validar, consultar base de datos y responder JSON.', 2),
    ('Validar en backend', 'El frontend ayuda, pero la validacion importante vive en backend porque una peticion puede venir de cualquier sitio.', 2),
    ('Codigos HTTP', '200 lee, 201 crea, 400 avisa datos malos, 404 no encuentra, 422 bloquea reglas especiales y 500 es fallo interno.', 2),
    ('Error 500', 'El servidor no debe ensenar SQL al usuario. Mejor un mensaje generico y revisar el log con calma.', 2),
    ('Modo denegado', 'Si una descripcion trae palabras bloqueadas, el backend corta la accion con 422 y devuelve un motivo claro.', 2),

    ('Componente', 'Un componente es una pieza de interfaz reutilizable. Si crece demasiado, probablemente pide una vista o subcomponente.', 3),
    ('Estado React', 'El estado guarda lo que cambia: formularios, listas, carta actual, usuario activo o mensajes de pantalla.', 3),
    ('api.js', 'Centralizar fetch evita repetir URLs por todas partes y hace mas facil corregir una llamada al backend.', 3),
    ('SweetAlert2', 'Los avisos importantes se ven mejor como modal: exito, error y resultado del juego quedan claros.', 3),
    ('Build', 'npm run build confirma que Vite puede compilar el frontend sin errores antes de entregar o desplegar.', 3),

    ('Clave primaria', 'La clave primaria identifica cada fila. Sin ella, encontrar un dato concreto se vuelve deporte extremo.', 4),
    ('Clave foranea', 'La clave foranea mantiene relaciones: una baraja pertenece a un usuario y una carta pertenece a una baraja.', 4),
    ('Seeds', 'Los seeds cargan datos iniciales para probar la app sin crear todo a mano cada vez.', 4),
    ('Relaciones', 'Si borras una baraja, revisa antes sus cartas y tarjetas. La base de datos no perdona el desorden.', 4),
    ('Enum', 'Un enum limita valores posibles. En cartas evita resultados inventados que el juego no sabria interpretar.', 4),

    ('Newman', 'Newman ejecuta la coleccion Postman desde terminal y permite comprobar la API como un cliente real.', 5),
    ('Docker Compose', 'Compose levanta varios servicios juntos: base de datos, backend y frontend, cada uno en su contenedor.', 5),
    ('Workflow CI', 'GitHub Actions instala dependencias, ejecuta tests y compila para detectar errores antes de fusionar.', 5),
    ('Variables env', 'Las variables de entorno separan configuracion sensible del codigo. Sin ellas, Docker suele ponerse dramatico.', 5),
    ('Release', 'Una release debe salir despues de comprobar tests, build, Postman y workflow. El boton bonito llega al final.', 5);
